# Software stack to demonstrate RA-TLS in combination with ECDSA-based attestation.

FROM ubuntu:16.04

# RUN sed -i 's/security\./old-releases\./g' /etc/apt/sources.list && sed -i 's/archive\./old-releases\./g' /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y --no-install-recommends clang-6.0 coreutils git wget openssh-client build-essential cmake libssl-dev libprotoc-dev protobuf-compiler libprotobuf-dev libprotobuf-c-dev protobuf-c-compiler autoconf libtool ca-certificates automake pkgconf vim-common
RUN ln -s /usr/bin/clang++-6.0 /usr/bin/clang++ && ln -s /usr/bin/clang-6.0 /usr/bin/clang
# Graphene requirements
RUN apt-get install -y --no-install-recommends python gawk python-protobuf python-crypto socat

# Install kernel headers so that Graphene can build the kernel module
# inside the container. The driver built inside the container is not
# actually used. The particular kernel version should not matter - just
# install a recent version.

RUN apt-get install -y --no-install-recommends linux-headers-$KERNEL_VERSION

RUN wget https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/libsgx-dcap-ql-dbg_1.0.101.48192-xenial1_amd64.deb \
    https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/libsgx-dcap-ql-dev_1.0.101.48192-xenial1_amd64.deb \
    https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/libsgx-dcap-ql_1.0.101.48192-xenial1_amd64.deb \
    https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/libsgx-enclave-common-dev_2.4.100.48163-xenial1_amd64.deb \
    https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/libsgx-enclave-common_2.4.100.48163-xenial1_amd64.deb \
    https://download.01.org/intel-sgx/dcap-1.0.1/dcap_installer/ubuntuServer1604/sgx_linux_x64_sdk_2.4.100.48163.bin

RUN dpkg -i libsgx-enclave-common_2.4.100.48163-xenial1_amd64.deb
RUN dpkg -i libsgx-enclave-common_2.4.100.48163-xenial1_amd64.deb libsgx-enclave-common-dev_2.4.100.48163-xenial1_amd64.deb
RUN dpkg -i libsgx-dcap-ql_1.0.101.48192-xenial1_amd64.deb
RUN dpkg -i libsgx-dcap-ql-dbg_1.0.101.48192-xenial1_amd64.deb libsgx-dcap-ql-dev_1.0.101.48192-xenial1_amd64.deb
RUN printf 'no\n/opt/intel\n' | bash sgx_linux_x64_sdk_2.4.100.48163.bin

RUN echo 'Defaults env_keep += "http_proxy https_proxy no_proxy"' >> /etc/sudoers
